FROM tensorflow/tensorflow:2.2.0-gpu
MAINTAINER taekyoon <tgchoi03@gmail.com>

RUN apt-get update -y \
&& apt-get install -y wget unzip language-pack-ko openjdk-8-jdk curl git-core locales

RUN apt-get install -y locales language-pack-ko
ENV LANG ko_KR.UTF-8
ENV LANGUAGE ko_KR:en
ENV LC_ALL ko_KR.UTF-8
RUN locale-gen ko_KR.UTF-8 \
&& update-locale LANG=ko_KR.UTF-8 \
&& dpkg-reconfigure locales

RUN apt install wget
RUN wget https://cmake.org/files/v3.14/cmake-3.14.3-Linux-x86_64.sh \
 && mkdir /opt/cmake \
 && sh cmake-3.14.3-Linux-x86_64.sh --prefix=/opt/cmake --skip-license \
 && ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake

RUN pip install --upgrade pip
RUN pip install konlpy cmake

COPY requirements_dkr.txt .
RUN pip install -r requirements_dkr.txt
RUN rm requirements_dkr.txt
RUN pip install setGPU
RUN python -c 'import nltk; nltk.download("punkt"); nltk.download("stopwords")'

EXPOSE 8889

WORKDIR /workspace/practice
ENTRYPOINT jupyter notebook --allow-root --ip=0.0.0.0 --port=8889 --no-browser && jupyter notebook list
